export const createStyles = (colors: any, isDarkTheme: boolean) => ({
  container: {
    flex: 1,
    backgroundColor: colors.containerBg,
  },
  header: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  title: {
    color: colors.primaryText,
    fontSize: 22,
    fontWeight: "bold" as const,
  },
  subtitle: {
    color: colors.secondaryText,
    marginTop: 6,
    fontSize: 14,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingHorizontal: 20,
  },
  emptyText: {
    color: colors.primaryText,
    fontSize: 16,
    textAlign: "center" as const,
  },
  list: {
    paddingBottom: 120,
    paddingHorizontal: 16,
  },
  card: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.borderColor,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: isDarkTheme ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardLeft: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(65,197,38,0.12)",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginRight: 12,
  },
  cardBody: {
    flex: 1,
  },
  identificadorText: {
    color: colors.primaryText,
    fontWeight: "600" as const,
    fontSize: 16,
  },
  identificadorSub: {
    color: colors.secondaryText,
    fontSize: 14,
    marginTop: 4,
  },
  fab: {
    position: "absolute" as const,
    right: 20,
    bottom: 28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#41C526",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    elevation: 8,
    shadowColor: "#41C526",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  loadingText: {
    color: colors.primaryText,
    fontSize: 18,
    fontWeight: "bold" as const,
    textAlign: "center" as const,
  },
  loadingSubtext: {
    color: colors.secondaryText,
    fontSize: 14,
    textAlign: "center" as const,
    marginTop: 8,
  },
});