import { useDarkColors } from "@/styles/theme-config";
import { StyleSheet } from "react-native";

export const createStyles = (colors: ReturnType<typeof useDarkColors>, isDarkTheme: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.containerBg,
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 10,
    gap: 0,
    paddingTop: 10,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.containerBg,
    justifyContent: "center",
    alignItems: "center",
  },
  errorContainer: {
    flex: 1,
    backgroundColor: colors.containerBg,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    color: "#FF6B6B",
    fontSize: 16,
    textAlign: "center",
  },
  inputContainer: {
    width: "90%",
    marginBottom: 8,
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  textInput: {
    fontSize: 16,
    color: isDarkTheme ? "#000" : "#000",
    backgroundColor: isDarkTheme ? "white" : "white",
    borderColor: "#41C526",
    borderWidth: 2,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingRight: 50,
    height: 48,
    textAlignVertical: 'center',
  },
  clearButton: {
    position: 'absolute',
    right: 15,
    top: '50%',
    marginTop: -10,
    paddingHorizontal: 5,
  },
  contentArea: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    width: "90%",
    height: "100%",
    marginTop: 16,
  },
  listArea: {
    display: "flex",
    flexDirection: "column",
    padding: 16,
    width: "100%",
    flex: 1,
    backgroundColor: colors.cardBg,
    borderRadius: 16,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: isDarkTheme ? 0.3 : 0.1,
    shadowRadius: 4.65,
    elevation: 8,
  },
  paginationContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginVertical: 20,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    marginTop: 16,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: isDarkTheme ? 0.2 : 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  pageText: {
    color: colors.primaryText,
    fontSize: 18,
    fontWeight: "600",
  },
  totalMotosContainer: {
    backgroundColor: "#41C526",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    alignItems: "center",
    shadowColor: "#41C526",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  emptyStateContainer: {
    padding: 40,
    alignItems: "center",
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    marginVertical: 20,
    borderWidth: 2,
    borderColor: "#41C526",
    borderStyle: "dashed",
  },
  emptyStateText: {
    color: colors.secondaryText,
    fontSize: 16,
    textAlign: "center",
  },
});
