import { useDarkColors } from "@/styles/theme-config";
import { StyleSheet } from "react-native";

<<<<<<< HEAD
export const createStyles = (
  colors: ReturnType<typeof useDarkColors>,
  isDarkTheme: boolean,
) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.containerBg,
    },
    text: {
      color: colors.primaryText,
      fontSize: 24,
      marginBottom: 16,
    },
    subtitle: {
      color: colors.secondaryText,
      fontSize: 18,
      marginBottom: 10,
    },
    button: {
      marginTop: 20,
    },
    profileSection: {
      backgroundColor: colors.cardBg,
      borderRadius: 12,
      padding: 20,
      marginBottom: 20,
      alignItems: "center",
      alignSelf: "center",
      width: "100%",
      maxWidth: 720,
      shadowColor: colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: isDarkTheme ? 0.3 : 0.1,
      shadowRadius: 4,
      elevation: 6,
    },
    userInfo: {
      alignItems: "center",
      width: "100%",
    },
    userName: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.primaryText,
      marginBottom: 8,
      textAlign: "center",
    },
    userEmail: {
      fontSize: 16,
      color: colors.secondaryText,
      marginBottom: 5,
    },
    userDetail: {
      fontSize: 14,
      color: colors.secondaryText,
      marginBottom: 3,
    },
    actionsSection: {
      backgroundColor: colors.cardBg,
      borderRadius: 12,
      padding: 20,
      alignSelf: "center",
      width: "100%",
      maxWidth: 720,
      shadowColor: colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: isDarkTheme ? 0.3 : 0.1,
      shadowRadius: 4,
      elevation: 6,
    },
    headerCard: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 18,
      paddingHorizontal: 10,
      marginBottom: 16,
    },
    headerCardVertical: {
      alignItems: "center",
      paddingVertical: 18,
      paddingHorizontal: 10,
      marginBottom: 16,
      alignSelf: "center",
      width: "100%",
      maxWidth: 720,
    },
    avatarWrap: {
      width: 96,
      height: 96,
      borderRadius: 48,
      borderWidth: 3,
      borderColor: colors.borderColor,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
      backgroundColor: colors.avatarBg,
    },
    avatarWrapVertical: {
      width: 108,
      height: 108,
      borderRadius: 54,
      borderWidth: 3,
      borderColor: colors.borderColor,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
      backgroundColor: colors.avatarBg,
    },
    headerText: {
      flex: 1,
    },
    headerTextVertical: {
      alignItems: "center",
    },
    userInfoGrid: {
      width: "100%",
    },
    infoRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.separatorColor,
    },
    infoLabel: {
      color: colors.infoLabelColor,
      fontSize: 14,
      width: "30%",
    },
    infoValue: {
      color: colors.primaryText,
      fontSize: 14,
      fontWeight: "600",
    },
  });
=======
export const createStyles = (colors: ReturnType<typeof useDarkColors>, isDarkTheme: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.containerBg,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  text: {
    color: colors.primaryText,
    fontSize: 24,
    marginBottom: 16,
  },
  subtitle: {
    color: colors.secondaryText,
    fontSize: 18,
    marginBottom: 10,
  },
  button: {
    marginTop: 20,
  },
  profileSection: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    alignItems: "center",
    alignSelf: "center",
    width: "100%",
    maxWidth: 720,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: isDarkTheme ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 6,
  },
  userInfo: {
    alignItems: "center",
    width: "100%",
  },
  userName: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.primaryText,
    marginBottom: 8,
    textAlign: "center",
  },
  userEmail: {
    fontSize: 16,
    color: colors.secondaryText,
    marginBottom: 5,
  },
  userDetail: {
    fontSize: 14,
    color: colors.secondaryText,
    marginBottom: 3,
  },
  actionsSection: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 20,
    alignSelf: "center",
    width: "100%",
    maxWidth: 720,
    shadowColor: colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: isDarkTheme ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 6,
  },
  headerCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 10,
    marginBottom: 16,
  },
  headerCardVertical: {
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 10,
    marginBottom: 16,
    alignSelf: "center",
    width: "100%",
    maxWidth: 720,
  },
  avatarWrap: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 3,
    borderColor: colors.borderColor,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    backgroundColor: colors.avatarBg,
  },
  avatarWrapVertical: {
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 3,
    borderColor: colors.borderColor,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    backgroundColor: colors.avatarBg,
  },
  headerText: {
    flex: 1,
  },
  headerTextVertical: {
    alignItems: "center",
  },
  userInfoGrid: {
    width: "100%",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.separatorColor,
  },
  infoLabel: {
    color: colors.infoLabelColor,
    fontSize: 14,
    width: "30%",
  },
  infoValue: {
    color: colors.primaryText,
    fontSize: 14,
    fontWeight: "600",
  },
});
>>>>>>> cee338f32f23dd48f4a42370af22eed620c488e4
