import { MotoView } from "./types/Moto";

export const motoViewMockList: MotoView[] = [
  {
    id: 1,
    uwb: 100,
    color: "black",
    motoData: {
      id: 1,
      nome: "Moto Sport",
      identificador: "ABC-9090",
      status: "Manutenção: Na área de conserto, motor quebrado",
      uwb: 100,
    },
  },
  {
    id: 2,
    uwb: 200,
    color: "black",
    motoData: {
      id: 2,
      nome: "Mottu E",
      identificador: "DOG-1010",
      status: "Problema no motor",
      uwb: 900,
    },
  },
  {
    id: 3,
    uwb: 300,
    color: "black",
    motoData: {
      id: 3,
      nome: "Mottu Pop",
      identificador: "ABC-1234",
      status: "Funcionando",
      uwb: 300,
    },
  },
  {
    id: 4,
    uwb: 400,
    color: "black",
    motoData: {
      id: 4,
      nome: "Mottu Pop",
      identificador: "DEF-5678",
      status: "Em manutenção",
      uwb: 400,
    },
  },
  {
    id: 5,
    uwb: 500,
    color: "black",
    motoData: {
      id: 5,
      nome: "Mottu Sport",
      identificador: "GHI-9012",
      status: "Disponível",
      uwb: 500,
    },
  },
  {
    id: 6,
    uwb: 600,
    color: "black",
    motoData: {
      id: 6,
      nome: "Mottu E",
      identificador: "JKL-3456",
      status: "Em manutenção",
      uwb: 600,
    },
  },
  {
    id: 7,
    uwb: 700,
    color: "black",
    motoData: {
      id: 7,
      nome: "Mottu Sport",
      identificador: "MNO-7890",
      status: "Disponível",
      uwb: 700,
    },
  },
  {
    id: 8,
    uwb: 800,
    color: "black",
    motoData: {
      id: 8,
      nome: "Mottu E",
      identificador: "PQR-1234",
      status: "Em manutenção",
      uwb: 800,
    },
  },
  {
    id: 9,
    uwb: 900,
    color: "black",
    motoData: {
      id: 9,
      nome: "Mottu Pop",
      identificador: "STU-5678",
      status: "Funcionando",
      uwb: 900,
    },
  },
  {
    id: 10,
    uwb: 1000,
    color: "black",
    motoData: {
      id: 10,
      nome: "Mottu Sport",
      identificador: "VWX-9012",
      status: "Problema no motor",
      uwb: 1000,
    },
  },
  {
    id: 11,
    uwb: 1100,
    color: "black",
    motoData: {
      id: 11,
      nome: "Mottu E",
      identificador: "YZA-3456",
      status: "Disponível",
      uwb: 1100,
    },
  },
  {
    id: 12,
    uwb: 1200,
    color: "black",
    motoData: {
      id: 12,
      nome: "Mottu Pop",
      identificador: "BCD-7890",
      status: "Em manutenção",
      uwb: 1200,
    },
  },
  {
    id: 13,
    uwb: 1300,
    color: "black",
    motoData: {
      id: 13,
      nome: "Mottu Sport",
      identificador: "EFG-1234",
      status: "Funcionando",
      uwb: 1300,
    },
  },
  {
    id: 14,
    uwb: 1400,
    color: "black",
    motoData: {
      id: 14,
      nome: "Mottu E",
      identificador: "HIJ-5678",
      status: "Problema no motor",
      uwb: 1400,
    },
  },
  {
    id: 15,
    uwb: 1500,
    color: "black",
    motoData: {
      id: 15,
      nome: "Mottu Pop",
      identificador: "KLM-9012",
      status: "Disponível",
      uwb: 1500,
    },
  },
  {
    id: 16,
    uwb: 1600,
    color: "black",
    motoData: {
      id: 16,
      nome: "Mottu Sport",
      identificador: "NOP-3456",
      status: "Em manutenção",
      uwb: 1600,
    },
  },
];
